language: node_js
cache: yarn
node_js:
  - 12

jobs:
  include:
    - stage: Test and produce Coverage
      node_js: node
      script: jest && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage