language: node_js
cache: yarn
node_js:
  - 12

before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

jobs:
  include:
    - stage: Test and produce Coverage
      node_js: node
      script: jest && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: Analyse License
      script:
        - fossa init
        - fossa analyze